mode: 'og_decoder'

model_params:
  input_dim: 1
  latent_dim: 8
  hidden_dim: 16

vae_chkpt: "/spaths/checkpoints/scene_vae.ckpt"


path_params:
  train_path: "/spaths/datasets/ddp_train_11f_32x32"
  test_path: "/spaths/datasets/ddp_test_11f_32x32"

loader_params:
  batch_size: 16
  num_workers: 4

exp_params:
  lr: 1.0e-4
  weight_decay: 0.0
  sched_gamma: 0.975

manual_seed: 1265

trainer_params:
  max_epochs: 100

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1265
