mode: 'scene_vae'

model_params:
  input_dim: 1
  latent_dim: 64

path_params:
  train_path: "/spaths/datasets/ddp_train_11f_32x32"
  test_path: "/spaths/datasets/ddp_test_11f_32x32"

loader_params:
  batch_size: 256
  num_workers: 4

exp_params:
  beta: 1.0
  kld_weight: 0.01
  lr: 0.001
  weight_decay: 0.0
  sched_gamma: 1.0

manual_seed: 1234

trainer_params:
  max_epochs: 100

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1234
