mode: 'scene_vae'

model_params:
  input_dim: 1
  latent_dim: 8
  hidden_dim: 16

path_params:
  train_path: "/spaths/datasets/ddp_train_11f_32x32"
  test_path: "/spaths/datasets/ddp_test_11f_32x32"

loader_params:
  batch_size: 32
  num_workers: 4

exp_params:
  beta: 1.0
  kld_weight: 1.0e-06
  lr: 5.0e-03
  weight_decay: 0.0
  sched_gamma: 0.975

manual_seed: 1234

trainer_params:
  max_epochs: 100

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1234
